import React,{useState} from 'react';
import Icon from '../components/Icon';
import {login,recover,resetPassword,googleLogin} from '../lib/auth';
const destinations={'Crie uma conta.':'/cadastro','Esqueceu a senha?':'/recuperar-senha','Termos de Serviço':'/termos','Política de Privacidade':'/privacidade','Termos de uso':'/termos','Política de privacidade':'/privacidade'};
export default function AuthScreens({path,navigate,onAuthenticated,onSessionCleared,notify}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[rememberMe,setRememberMe]=useState(false);
 const loginPage=path==='/login';
 function link(label,route){return <a href={route||destinations[label]||'#'} onClick={e=>{e.preventDefault();const target=route||destinations[label];target?navigate(target):notify(`“${label}” não faz parte das telas enviadas.`)}}>{label}</a>}
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{if(loginPage){const user=await login({email,password,rememberMe});if(!user)throw Error('A autenticação não retornou uma conta.');onAuthenticated(user)}else if(path==='/recuperar-senha'){setResult(await recover(email))}else{const token=new URLSearchParams(location.search).get('token');await resetPassword({token,password,confirmation});onSessionCleared?.();navigate('/login');notify('Senha atualizada. Entre com a nova senha.')}}catch(e){setError(e.message||'Não foi possível concluir. Tente novamente.')}finally{setBusy(false)}}
 const footer=<footer className="recovery-footer"><div>{link('Sobre nós')}<span>|</span>{link('Termos de uso')}<span>|</span>{link('Política de privacidade')}<span>|</span>{link('Central de ajuda')}</div><p>© Palco. Todos os direitos reservados.</p></footer>;
 if(loginPage)return <div className="page auth-login-page"><main className="main"><section className="login" aria-labelledby="login-title"><div className="brand"><h1 id="login-title">Palco</h1><p>Onde talentos encontram oportunidades.</p></div>{error&&<div className="login-error" role="alert"><span>⚠</span><div><b>{error.startsWith('E-mail')?'E-mail ou senha incorretos.':error}</b>{error.startsWith('E-mail')&&<small>Verifique os dados e tente novamente.</small>}</div></div>}<form onSubmit={submit}><div className="field"><label htmlFor="email">E-mail</label><input id="email" name="email" type="email" autoComplete="username" placeholder="Email@example.com" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field password-field"><label htmlFor="password">Senha</label><div className="password-input"><input id="password" name="password" type={visible?'text':'password'} autoComplete="current-password" placeholder="Senha" required value={password} onChange={e=>setPassword(e.target.value)}/><button className="eye" type="button" aria-label={visible?'Ocultar senha':'Mostrar senha'} aria-pressed={visible} onClick={()=>setVisible(!visible)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M2 12s3-8 10-8 10 8 10 8-3 8-10 8S2 12 2 12Z"/><circle cx="12" cy="12" r="3.5"/>{visible&&<path d="m3 3 18 18"/>}</svg></button></div></div><label><input type="checkbox" checked={rememberMe} onChange={e=>setRememberMe(e.target.checked)}/> Lembrar de mim</label><div className="forgot">{link('Esqueceu a senha?')}</div><button className="submit" disabled={busy}>{busy?'Entrando…':'Entrar'}</button><button className="google" type="button" disabled={busy} onClick={async()=>{setError('');try{await googleLogin()}catch(e){setError(e.message)}}}><img src="/assets/google.png" alt=""/>Continuar com google</button></form><p className="signup">Ainda não está na Palco? {link('Crie uma conta.')}</p><p className="terms">Ao continuar, você concorda com os {link('Termos de Serviço')} do Palco e confirma que leu nossa {link('Política de Privacidade')}. Aviso na coleta de informações.</p></section></main></div>;
 return <main className="recovery-page"><section className={'recovery-card '+(path==='/redefinir-senha'?'reset-card':'')}><a className="recovery-back" href="/login" onClick={e=>{e.preventDefault();navigate('/login')}}><Icon name="arrow"/>Voltar à tela inicial</a><h1>{path==='/recuperar-senha'?'Encontre sua conta':'Atualizar senha'}</h1><p>{path==='/recuperar-senha'?'Digite o e-mail vinculado à sua conta para receber as instruções de redefinição de senha.':'Insira uma senha nova. Então, você será redirecionado para a página de login.'}</p><form onSubmit={submit}>{path==='/recuperar-senha'?<><label className="sr-only" htmlFor="recovery-email">E-mail da conta</label><input id="recovery-email" type="email" placeholder="Email@example.com" value={email} autoComplete="email" onChange={e=>setEmail(e.target.value)} required/></>:<><label htmlFor="new-password">Senha nova</label><input id="new-password" type="password" autoComplete="new-password" placeholder="Senha nova" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><label htmlFor="confirm-password">Confirmar senha</label><input id="confirm-password" type="password" autoComplete="new-password" placeholder="Confirmar senha" minLength={8} value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></>}{error&&<p className="auth-form-error" role="alert">{error}</p>}{result&&<div className="recovery-result" role="status"><p>{result.message}</p></div>}<button className="yellow" disabled={busy}>{busy?'Aguarde…':path==='/recuperar-senha'?'Enviar':'Redefinir senha'}</button></form>{footer}</section></main>
}
